//----------------------------------------------------------------------------------
// File:        NvGLESWrapper/NvWinES31AEP.h
// SDK Version: v3.00 
// Email:       gameworks@nvidia.com
// Site:        http://developer.nvidia.com/
//
// Copyright (c) 2014-2015, NVIDIA CORPORATION. All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
//  * Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
//  * Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
//  * Neither the name of NVIDIA CORPORATION nor the names of its
//    contributors may be used to endorse or promote products derived
//    from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS ``AS IS'' AND ANY
// EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
// PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR
// CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
// EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
// PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
// PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
// OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
//----------------------------------------------------------------------------------
#ifndef __NvWinES31AEP_h_
#define __NvWinES31AEP_h_ 1

#ifdef __cplusplus
extern "C" {
#endif

/* Generated on date 20140807 */


#ifndef GL_KHR_blend_equation_advanced
#define GL_KHR_blend_equation_advanced 1
#ifndef GL_BLEND_ADVANCED_COHERENT_KHR
#define GL_BLEND_ADVANCED_COHERENT_KHR    GL_BLEND_ADVANCED_COHERENT
#endif
#ifndef GL_MULTIPLY_KHR
#define GL_MULTIPLY_KHR                   GL_MULTIPLY
#endif
#ifndef GL_SCREEN_KHR
#define GL_SCREEN_KHR                     GL_SCREEN
#endif
#ifndef GL_OVERLAY_KHR
#define GL_OVERLAY_KHR                    GL_OVERLAY
#endif
#ifndef GL_DARKEN_KHR
#define GL_DARKEN_KHR                     GL_DARKEN
#endif
#ifndef GL_LIGHTEN_KHR
#define GL_LIGHTEN_KHR                    GL_LIGHTEN
#endif
#ifndef GL_COLORDODGE_KHR
#define GL_COLORDODGE_KHR                 GL_COLORDODGE
#endif
#ifndef GL_COLORBURN_KHR
#define GL_COLORBURN_KHR                  GL_COLORBURN
#endif
#ifndef GL_HARDLIGHT_KHR
#define GL_HARDLIGHT_KHR                  GL_HARDLIGHT
#endif
#ifndef GL_SOFTLIGHT_KHR
#define GL_SOFTLIGHT_KHR                  GL_SOFTLIGHT
#endif
#ifndef GL_DIFFERENCE_KHR
#define GL_DIFFERENCE_KHR                 GL_DIFFERENCE
#endif
#ifndef GL_EXCLUSION_KHR
#define GL_EXCLUSION_KHR                  GL_EXCLUSION
#endif
#ifndef GL_HSL_HUE_KHR
#define GL_HSL_HUE_KHR                    GL_HSL_HUE
#endif
#ifndef GL_HSL_SATURATION_KHR
#define GL_HSL_SATURATION_KHR             GL_HSL_SATURATION
#endif
#ifndef GL_HSL_COLOR_KHR
#define GL_HSL_COLOR_KHR                  GL_HSL_COLOR
#endif
#ifndef GL_HSL_LUMINOSITY_KHR
#define GL_HSL_LUMINOSITY_KHR             GL_HSL_LUMINOSITY
#endif
#ifndef glBlendBarrierKHR
#define glBlendBarrierKHR                 glBlendBarrier
#endif
#endif /* GL_KHR_blend_equation_advanced */

#ifndef GL_KHR_debug
#define GL_KHR_debug 1
#ifndef GL_DEBUG_OUTPUT_SYNCHRONOUS_KHR
#define GL_DEBUG_OUTPUT_SYNCHRONOUS_KHR   GL_DEBUG_OUTPUT_SYNCHRONOUS
#endif
#ifndef GL_DEBUG_NEXT_LOGGED_MESSAGE_LENGTH_KHR
#define GL_DEBUG_NEXT_LOGGED_MESSAGE_LENGTH_KHR GL_DEBUG_NEXT_LOGGED_MESSAGE_LENGTH
#endif
#ifndef GL_DEBUG_CALLBACK_FUNCTION_KHR
#define GL_DEBUG_CALLBACK_FUNCTION_KHR    GL_DEBUG_CALLBACK_FUNCTION
#endif
#ifndef GL_DEBUG_CALLBACK_USER_PARAM_KHR
#define GL_DEBUG_CALLBACK_USER_PARAM_KHR  GL_DEBUG_CALLBACK_USER_PARAM
#endif
#ifndef GL_DEBUG_SOURCE_API_KHR
#define GL_DEBUG_SOURCE_API_KHR           GL_DEBUG_SOURCE_API
#endif
#ifndef GL_DEBUG_SOURCE_WINDOW_SYSTEM_KHR
#define GL_DEBUG_SOURCE_WINDOW_SYSTEM_KHR GL_DEBUG_SOURCE_WINDOW_SYSTEM
#endif
#ifndef GL_DEBUG_SOURCE_SHADER_COMPILER_KHR
#define GL_DEBUG_SOURCE_SHADER_COMPILER_KHR GL_DEBUG_SOURCE_SHADER_COMPILER
#endif
#ifndef GL_DEBUG_SOURCE_THIRD_PARTY_KHR
#define GL_DEBUG_SOURCE_THIRD_PARTY_KHR   GL_DEBUG_SOURCE_THIRD_PARTY
#endif
#ifndef GL_DEBUG_SOURCE_APPLICATION_KHR
#define GL_DEBUG_SOURCE_APPLICATION_KHR   GL_DEBUG_SOURCE_APPLICATION
#endif
#ifndef GL_DEBUG_SOURCE_OTHER_KHR
#define GL_DEBUG_SOURCE_OTHER_KHR         GL_DEBUG_SOURCE_OTHER
#endif
#ifndef GL_DEBUG_TYPE_ERROR_KHR
#define GL_DEBUG_TYPE_ERROR_KHR           GL_DEBUG_TYPE_ERROR
#endif
#ifndef GL_DEBUG_TYPE_DEPRECATED_BEHAVIOR_KHR
#define GL_DEBUG_TYPE_DEPRECATED_BEHAVIOR_KHR GL_DEBUG_TYPE_DEPRECATED_BEHAVIOR
#endif
#ifndef GL_DEBUG_TYPE_UNDEFINED_BEHAVIOR_KHR
#define GL_DEBUG_TYPE_UNDEFINED_BEHAVIOR_KHR GL_DEBUG_TYPE_UNDEFINED_BEHAVIOR
#endif
#ifndef GL_DEBUG_TYPE_PORTABILITY_KHR
#define GL_DEBUG_TYPE_PORTABILITY_KHR     GL_DEBUG_TYPE_PORTABILITY
#endif
#ifndef GL_DEBUG_TYPE_PERFORMANCE_KHR
#define GL_DEBUG_TYPE_PERFORMANCE_KHR     GL_DEBUG_TYPE_PERFORMANCE
#endif
#ifndef GL_DEBUG_TYPE_OTHER_KHR
#define GL_DEBUG_TYPE_OTHER_KHR           GL_DEBUG_TYPE_OTHER
#endif
#ifndef GL_DEBUG_TYPE_MARKER_KHR
#define GL_DEBUG_TYPE_MARKER_KHR          GL_DEBUG_TYPE_MARKER
#endif
#ifndef GL_DEBUG_TYPE_PUSH_GROUP_KHR
#define GL_DEBUG_TYPE_PUSH_GROUP_KHR      GL_DEBUG_TYPE_PUSH_GROUP
#endif
#ifndef GL_DEBUG_TYPE_POP_GROUP_KHR
#define GL_DEBUG_TYPE_POP_GROUP_KHR       GL_DEBUG_TYPE_POP_GROUP
#endif
#ifndef GL_DEBUG_SEVERITY_NOTIFICATION_KHR
#define GL_DEBUG_SEVERITY_NOTIFICATION_KHR GL_DEBUG_SEVERITY_NOTIFICATION
#endif
#ifndef GL_MAX_DEBUG_GROUP_STACK_DEPTH_KHR
#define GL_MAX_DEBUG_GROUP_STACK_DEPTH_KHR GL_MAX_DEBUG_GROUP_STACK_DEPTH
#endif
#ifndef GL_DEBUG_GROUP_STACK_DEPTH_KHR
#define GL_DEBUG_GROUP_STACK_DEPTH_KHR    GL_DEBUG_GROUP_STACK_DEPTH
#endif
#ifndef GL_BUFFER_KHR
#define GL_BUFFER_KHR                     GL_BUFFER
#endif
#ifndef GL_SHADER_KHR
#define GL_SHADER_KHR                     GL_SHADER
#endif
#ifndef GL_PROGRAM_KHR
#define GL_PROGRAM_KHR                    GL_PROGRAM
#endif
#ifndef GL_VERTEX_ARRAY_KHR
#define GL_VERTEX_ARRAY_KHR               GL_VERTEX_ARRAY
#endif
#ifndef GL_QUERY_KHR
#define GL_QUERY_KHR                      GL_QUERY
#endif
#ifndef GL_SAMPLER_KHR
#define GL_SAMPLER_KHR                    GL_SAMPLER
#endif
#ifndef GL_MAX_LABEL_LENGTH_KHR
#define GL_MAX_LABEL_LENGTH_KHR           GL_MAX_LABEL_LENGTH
#endif
#ifndef GL_MAX_DEBUG_MESSAGE_LENGTH_KHR
#define GL_MAX_DEBUG_MESSAGE_LENGTH_KHR   GL_MAX_DEBUG_MESSAGE_LENGTH
#endif
#ifndef GL_MAX_DEBUG_LOGGED_MESSAGES_KHR
#define GL_MAX_DEBUG_LOGGED_MESSAGES_KHR  GL_MAX_DEBUG_LOGGED_MESSAGES
#endif
#ifndef GL_DEBUG_LOGGED_MESSAGES_KHR
#define GL_DEBUG_LOGGED_MESSAGES_KHR      GL_DEBUG_LOGGED_MESSAGES
#endif
#ifndef GL_DEBUG_SEVERITY_HIGH_KHR
#define GL_DEBUG_SEVERITY_HIGH_KHR        GL_DEBUG_SEVERITY_HIGH
#endif
#ifndef GL_DEBUG_SEVERITY_MEDIUM_KHR
#define GL_DEBUG_SEVERITY_MEDIUM_KHR      GL_DEBUG_SEVERITY_MEDIUM
#endif
#ifndef GL_DEBUG_SEVERITY_LOW_KHR
#define GL_DEBUG_SEVERITY_LOW_KHR         GL_DEBUG_SEVERITY_LOW
#endif
#ifndef GL_DEBUG_OUTPUT_KHR
#define GL_DEBUG_OUTPUT_KHR               GL_DEBUG_OUTPUT
#endif
#ifndef GL_CONTEXT_FLAG_DEBUG_BIT_KHR
#define GL_CONTEXT_FLAG_DEBUG_BIT_KHR     GL_CONTEXT_FLAG_DEBUG_BIT
#endif
#ifndef GL_STACK_OVERFLOW_KHR
#define GL_STACK_OVERFLOW_KHR             GL_STACK_OVERFLOW
#endif
#ifndef GL_STACK_UNDERFLOW_KHR
#define GL_STACK_UNDERFLOW_KHR            GL_STACK_UNDERFLOW
#endif
#ifndef glDebugMessageControlKHR
#define glDebugMessageControlKHR          glDebugMessageControl
#endif
#ifndef glDebugMessageInsertKHR
#define glDebugMessageInsertKHR           glDebugMessageInsert
#endif
#ifndef glDebugMessageCallbackKHR
#define glDebugMessageCallbackKHR         glDebugMessageCallback
#endif
#ifndef glGetDebugMessageLogKHR
#define glGetDebugMessageLogKHR           glGetDebugMessageLog
#endif
#ifndef glPushDebugGroupKHR
#define glPushDebugGroupKHR               glPushDebugGroup
#endif
#ifndef glPopDebugGroupKHR
#define glPopDebugGroupKHR                glPopDebugGroup
#endif
#ifndef glObjectLabelKHR
#define glObjectLabelKHR                  glObjectLabel
#endif
#ifndef glGetObjectLabelKHR
#define glGetObjectLabelKHR               glGetObjectLabel
#endif
#ifndef glObjectPtrLabelKHR
#define glObjectPtrLabelKHR               glObjectPtrLabel
#endif
#ifndef glGetObjectPtrLabelKHR
#define glGetObjectPtrLabelKHR            glGetObjectPtrLabel
#endif
#ifndef glGetPointervKHR
#define glGetPointervKHR                  glGetPointerv
#endif
#endif /* GL_KHR_debug */

#ifndef GL_KHR_texture_compression_astc_ldr
#define GL_KHR_texture_compression_astc_ldr 1
#ifndef GL_COMPRESSED_RGBA_ASTC_4x4_KHR
#define GL_COMPRESSED_RGBA_ASTC_4x4_KHR   GL_COMPRESSED_RGBA_ASTC_4x4
#endif
#ifndef GL_COMPRESSED_RGBA_ASTC_5x4_KHR
#define GL_COMPRESSED_RGBA_ASTC_5x4_KHR   GL_COMPRESSED_RGBA_ASTC_5x4
#endif
#ifndef GL_COMPRESSED_RGBA_ASTC_5x5_KHR
#define GL_COMPRESSED_RGBA_ASTC_5x5_KHR   GL_COMPRESSED_RGBA_ASTC_5x5
#endif
#ifndef GL_COMPRESSED_RGBA_ASTC_6x5_KHR
#define GL_COMPRESSED_RGBA_ASTC_6x5_KHR   GL_COMPRESSED_RGBA_ASTC_6x5
#endif
#ifndef GL_COMPRESSED_RGBA_ASTC_6x6_KHR
#define GL_COMPRESSED_RGBA_ASTC_6x6_KHR   GL_COMPRESSED_RGBA_ASTC_6x6
#endif
#ifndef GL_COMPRESSED_RGBA_ASTC_8x5_KHR
#define GL_COMPRESSED_RGBA_ASTC_8x5_KHR   GL_COMPRESSED_RGBA_ASTC_8x5
#endif
#ifndef GL_COMPRESSED_RGBA_ASTC_8x6_KHR
#define GL_COMPRESSED_RGBA_ASTC_8x6_KHR   GL_COMPRESSED_RGBA_ASTC_8x6
#endif
#ifndef GL_COMPRESSED_RGBA_ASTC_8x8_KHR
#define GL_COMPRESSED_RGBA_ASTC_8x8_KHR   GL_COMPRESSED_RGBA_ASTC_8x8
#endif
#ifndef GL_COMPRESSED_RGBA_ASTC_10x5_KHR
#define GL_COMPRESSED_RGBA_ASTC_10x5_KHR  GL_COMPRESSED_RGBA_ASTC_10x5
#endif
#ifndef GL_COMPRESSED_RGBA_ASTC_10x6_KHR
#define GL_COMPRESSED_RGBA_ASTC_10x6_KHR  GL_COMPRESSED_RGBA_ASTC_10x6
#endif
#ifndef GL_COMPRESSED_RGBA_ASTC_10x8_KHR
#define GL_COMPRESSED_RGBA_ASTC_10x8_KHR  GL_COMPRESSED_RGBA_ASTC_10x8
#endif
#ifndef GL_COMPRESSED_RGBA_ASTC_10x10_KHR
#define GL_COMPRESSED_RGBA_ASTC_10x10_KHR GL_COMPRESSED_RGBA_ASTC_10x10
#endif
#ifndef GL_COMPRESSED_RGBA_ASTC_12x10_KHR
#define GL_COMPRESSED_RGBA_ASTC_12x10_KHR GL_COMPRESSED_RGBA_ASTC_12x10
#endif
#ifndef GL_COMPRESSED_RGBA_ASTC_12x12_KHR
#define GL_COMPRESSED_RGBA_ASTC_12x12_KHR GL_COMPRESSED_RGBA_ASTC_12x12
#endif
#ifndef GL_COMPRESSED_SRGB8_ALPHA8_ASTC_4x4_KHR
#define GL_COMPRESSED_SRGB8_ALPHA8_ASTC_4x4_KHR GL_COMPRESSED_SRGB8_ALPHA8_ASTC_4x4
#endif
#ifndef GL_COMPRESSED_SRGB8_ALPHA8_ASTC_5x4_KHR
#define GL_COMPRESSED_SRGB8_ALPHA8_ASTC_5x4_KHR GL_COMPRESSED_SRGB8_ALPHA8_ASTC_5x4
#endif
#ifndef GL_COMPRESSED_SRGB8_ALPHA8_ASTC_5x5_KHR
#define GL_COMPRESSED_SRGB8_ALPHA8_ASTC_5x5_KHR GL_COMPRESSED_SRGB8_ALPHA8_ASTC_5x5
#endif
#ifndef GL_COMPRESSED_SRGB8_ALPHA8_ASTC_6x5_KHR
#define GL_COMPRESSED_SRGB8_ALPHA8_ASTC_6x5_KHR GL_COMPRESSED_SRGB8_ALPHA8_ASTC_6x5
#endif
#ifndef GL_COMPRESSED_SRGB8_ALPHA8_ASTC_6x6_KHR
#define GL_COMPRESSED_SRGB8_ALPHA8_ASTC_6x6_KHR GL_COMPRESSED_SRGB8_ALPHA8_ASTC_6x6
#endif
#ifndef GL_COMPRESSED_SRGB8_ALPHA8_ASTC_8x5_KHR
#define GL_COMPRESSED_SRGB8_ALPHA8_ASTC_8x5_KHR GL_COMPRESSED_SRGB8_ALPHA8_ASTC_8x5
#endif
#ifndef GL_COMPRESSED_SRGB8_ALPHA8_ASTC_8x6_KHR
#define GL_COMPRESSED_SRGB8_ALPHA8_ASTC_8x6_KHR GL_COMPRESSED_SRGB8_ALPHA8_ASTC_8x6
#endif
#ifndef GL_COMPRESSED_SRGB8_ALPHA8_ASTC_8x8_KHR
#define GL_COMPRESSED_SRGB8_ALPHA8_ASTC_8x8_KHR GL_COMPRESSED_SRGB8_ALPHA8_ASTC_8x8
#endif
#ifndef GL_COMPRESSED_SRGB8_ALPHA8_ASTC_10x5_KHR
#define GL_COMPRESSED_SRGB8_ALPHA8_ASTC_10x5_KHR GL_COMPRESSED_SRGB8_ALPHA8_ASTC_10x5
#endif
#ifndef GL_COMPRESSED_SRGB8_ALPHA8_ASTC_10x6_KHR
#define GL_COMPRESSED_SRGB8_ALPHA8_ASTC_10x6_KHR GL_COMPRESSED_SRGB8_ALPHA8_ASTC_10x6
#endif
#ifndef GL_COMPRESSED_SRGB8_ALPHA8_ASTC_10x8_KHR
#define GL_COMPRESSED_SRGB8_ALPHA8_ASTC_10x8_KHR GL_COMPRESSED_SRGB8_ALPHA8_ASTC_10x8
#endif
#ifndef GL_COMPRESSED_SRGB8_ALPHA8_ASTC_10x10_KHR
#define GL_COMPRESSED_SRGB8_ALPHA8_ASTC_10x10_KHR GL_COMPRESSED_SRGB8_ALPHA8_ASTC_10x10
#endif
#ifndef GL_COMPRESSED_SRGB8_ALPHA8_ASTC_12x10_KHR
#define GL_COMPRESSED_SRGB8_ALPHA8_ASTC_12x10_KHR GL_COMPRESSED_SRGB8_ALPHA8_ASTC_12x10
#endif
#ifndef GL_COMPRESSED_SRGB8_ALPHA8_ASTC_12x12_KHR
#define GL_COMPRESSED_SRGB8_ALPHA8_ASTC_12x12_KHR GL_COMPRESSED_SRGB8_ALPHA8_ASTC_12x12
#endif
#endif /* GL_KHR_texture_compression_astc_ldr */

#ifndef GL_OES_sample_shading
#define GL_OES_sample_shading 1
#ifndef GL_SAMPLE_SHADING_OES
#define GL_SAMPLE_SHADING_OES             GL_SAMPLE_SHADING
#endif
#ifndef GL_MIN_SAMPLE_SHADING_VALUE_OES
#define GL_MIN_SAMPLE_SHADING_VALUE_OES   GL_MIN_SAMPLE_SHADING_VALUE
#endif
#ifndef glMinSampleShadingOES
#define glMinSampleShadingOES             glMinSampleShading
#endif
#endif /* GL_OES_sample_shading */

#ifndef GL_OES_sample_variables
#define GL_OES_sample_variables 1
#endif /* GL_OES_sample_variables */

#ifndef GL_OES_shader_image_atomic
#define GL_OES_shader_image_atomic 1
#endif /* GL_OES_shader_image_atomic */

#ifndef GL_OES_shader_multisample_interpolation
#define GL_OES_shader_multisample_interpolation 1
#ifndef GL_MIN_FRAGMENT_INTERPOLATION_OFFSET_OES
#define GL_MIN_FRAGMENT_INTERPOLATION_OFFSET_OES GL_MIN_FRAGMENT_INTERPOLATION_OFFSET
#endif
#ifndef GL_MAX_FRAGMENT_INTERPOLATION_OFFSET_OES
#define GL_MAX_FRAGMENT_INTERPOLATION_OFFSET_OES GL_MAX_FRAGMENT_INTERPOLATION_OFFSET
#endif
#ifndef GL_FRAGMENT_INTERPOLATION_OFFSET_BITS_OES
#define GL_FRAGMENT_INTERPOLATION_OFFSET_BITS_OES GL_FRAGMENT_INTERPOLATION_OFFSET_BITS
#endif
#endif /* GL_OES_shader_multisample_interpolation */

#ifndef GL_OES_texture_stencil8
#define GL_OES_texture_stencil8 1
#ifndef GL_STENCIL_INDEX_OES
#define GL_STENCIL_INDEX_OES              GL_STENCIL_INDEX
#endif
#ifndef GL_STENCIL_INDEX8_OES
#define GL_STENCIL_INDEX8_OES             GL_STENCIL_INDEX8
#endif
#endif /* GL_OES_texture_stencil8 */

#ifndef GL_OES_texture_storage_multisample_2d_array
#define GL_OES_texture_storage_multisample_2d_array 1
#ifndef GL_TEXTURE_2D_MULTISAMPLE_ARRAY_OES
#define GL_TEXTURE_2D_MULTISAMPLE_ARRAY_OES GL_TEXTURE_2D_MULTISAMPLE_ARRAY
#endif
#ifndef GL_TEXTURE_BINDING_2D_MULTISAMPLE_ARRAY_OES
#define GL_TEXTURE_BINDING_2D_MULTISAMPLE_ARRAY_OES GL_TEXTURE_BINDING_2D_MULTISAMPLE_ARRAY
#endif
#ifndef GL_SAMPLER_2D_MULTISAMPLE_ARRAY_OES
#define GL_SAMPLER_2D_MULTISAMPLE_ARRAY_OES GL_SAMPLER_2D_MULTISAMPLE_ARRAY
#endif
#ifndef GL_INT_SAMPLER_2D_MULTISAMPLE_ARRAY_OES
#define GL_INT_SAMPLER_2D_MULTISAMPLE_ARRAY_OES GL_INT_SAMPLER_2D_MULTISAMPLE_ARRAY
#endif
#ifndef GL_UNSIGNED_INT_SAMPLER_2D_MULTISAMPLE_ARRAY_OES
#define GL_UNSIGNED_INT_SAMPLER_2D_MULTISAMPLE_ARRAY_OES GL_UNSIGNED_INT_SAMPLER_2D_MULTISAMPLE_ARRAY
#endif
#ifndef glTexStorage3DMultisampleOES
#define glTexStorage3DMultisampleOES      glTexStorage3DMultisample
#endif
#endif /* GL_OES_texture_storage_multisample_2d_array */

#ifndef GL_EXT_copy_image
#define GL_EXT_copy_image 1
#ifndef glCopyImageSubDataEXT
#define glCopyImageSubDataEXT             glCopyImageSubData
#endif
#endif /* GL_EXT_copy_image */

#ifndef GL_EXT_draw_buffers_indexed
#define GL_EXT_draw_buffers_indexed 1




























#ifndef glEnableiEXT
#define glEnableiEXT                      glEnablei
#endif
#ifndef glDisableiEXT
#define glDisableiEXT                     glDisablei
#endif
#ifndef glBlendEquationiEXT
#define glBlendEquationiEXT               glBlendEquationi
#endif
#ifndef glBlendEquationSeparateiEXT
#define glBlendEquationSeparateiEXT       glBlendEquationSeparatei
#endif
#ifndef glBlendFunciEXT
#define glBlendFunciEXT                   glBlendFunci
#endif
#ifndef glBlendFuncSeparateiEXT
#define glBlendFuncSeparateiEXT           glBlendFuncSeparatei
#endif
#ifndef glColorMaskiEXT
#define glColorMaskiEXT                   glColorMaski
#endif
#ifndef glIsEnablediEXT
#define glIsEnablediEXT                   glIsEnabledi
#endif
#endif /* GL_EXT_draw_buffers_indexed */

#ifndef GL_EXT_geometry_shader
#define GL_EXT_geometry_shader 1
#ifndef GL_GEOMETRY_SHADER_EXT
#define GL_GEOMETRY_SHADER_EXT            GL_GEOMETRY_SHADER
#endif
#ifndef GL_GEOMETRY_SHADER_BIT_EXT
#define GL_GEOMETRY_SHADER_BIT_EXT        GL_GEOMETRY_SHADER_BIT
#endif
#ifndef GL_GEOMETRY_LINKED_VERTICES_OUT_EXT
#define GL_GEOMETRY_LINKED_VERTICES_OUT_EXT GL_GEOMETRY_LINKED_VERTICES_OUT
#endif
#ifndef GL_GEOMETRY_LINKED_INPUT_TYPE_EXT
#define GL_GEOMETRY_LINKED_INPUT_TYPE_EXT GL_GEOMETRY_LINKED_INPUT_TYPE
#endif
#ifndef GL_GEOMETRY_LINKED_OUTPUT_TYPE_EXT
#define GL_GEOMETRY_LINKED_OUTPUT_TYPE_EXT GL_GEOMETRY_LINKED_OUTPUT_TYPE
#endif
#ifndef GL_GEOMETRY_SHADER_INVOCATIONS_EXT
#define GL_GEOMETRY_SHADER_INVOCATIONS_EXT GL_GEOMETRY_SHADER_INVOCATIONS
#endif
#ifndef GL_LAYER_PROVOKING_VERTEX_EXT
#define GL_LAYER_PROVOKING_VERTEX_EXT     GL_LAYER_PROVOKING_VERTEX
#endif
#ifndef GL_LINES_ADJACENCY_EXT
#define GL_LINES_ADJACENCY_EXT            GL_LINES_ADJACENCY
#endif
#ifndef GL_LINE_STRIP_ADJACENCY_EXT
#define GL_LINE_STRIP_ADJACENCY_EXT       GL_LINE_STRIP_ADJACENCY
#endif
#ifndef GL_TRIANGLES_ADJACENCY_EXT
#define GL_TRIANGLES_ADJACENCY_EXT        GL_TRIANGLES_ADJACENCY
#endif
#ifndef GL_TRIANGLE_STRIP_ADJACENCY_EXT
#define GL_TRIANGLE_STRIP_ADJACENCY_EXT   GL_TRIANGLE_STRIP_ADJACENCY
#endif
#ifndef GL_MAX_GEOMETRY_UNIFORM_COMPONENTS_EXT
#define GL_MAX_GEOMETRY_UNIFORM_COMPONENTS_EXT GL_MAX_GEOMETRY_UNIFORM_COMPONENTS
#endif
#ifndef GL_MAX_GEOMETRY_UNIFORM_BLOCKS_EXT
#define GL_MAX_GEOMETRY_UNIFORM_BLOCKS_EXT GL_MAX_GEOMETRY_UNIFORM_BLOCKS
#endif
#ifndef GL_MAX_COMBINED_GEOMETRY_UNIFORM_COMPONENTS_EXT
#define GL_MAX_COMBINED_GEOMETRY_UNIFORM_COMPONENTS_EXT GL_MAX_COMBINED_GEOMETRY_UNIFORM_COMPONENTS
#endif
#ifndef GL_MAX_GEOMETRY_INPUT_COMPONENTS_EXT
#define GL_MAX_GEOMETRY_INPUT_COMPONENTS_EXT GL_MAX_GEOMETRY_INPUT_COMPONENTS
#endif
#ifndef GL_MAX_GEOMETRY_OUTPUT_COMPONENTS_EXT
#define GL_MAX_GEOMETRY_OUTPUT_COMPONENTS_EXT GL_MAX_GEOMETRY_OUTPUT_COMPONENTS
#endif
#ifndef GL_MAX_GEOMETRY_OUTPUT_VERTICES_EXT
#define GL_MAX_GEOMETRY_OUTPUT_VERTICES_EXT GL_MAX_GEOMETRY_OUTPUT_VERTICES
#endif
#ifndef GL_MAX_GEOMETRY_TOTAL_OUTPUT_COMPONENTS_EXT
#define GL_MAX_GEOMETRY_TOTAL_OUTPUT_COMPONENTS_EXT GL_MAX_GEOMETRY_TOTAL_OUTPUT_COMPONENTS
#endif
#ifndef GL_MAX_GEOMETRY_SHADER_INVOCATIONS_EXT
#define GL_MAX_GEOMETRY_SHADER_INVOCATIONS_EXT GL_MAX_GEOMETRY_SHADER_INVOCATIONS
#endif
#ifndef GL_MAX_GEOMETRY_TEXTURE_IMAGE_UNITS_EXT
#define GL_MAX_GEOMETRY_TEXTURE_IMAGE_UNITS_EXT GL_MAX_GEOMETRY_TEXTURE_IMAGE_UNITS
#endif
#ifndef GL_MAX_GEOMETRY_ATOMIC_COUNTER_BUFFERS_EXT
#define GL_MAX_GEOMETRY_ATOMIC_COUNTER_BUFFERS_EXT GL_MAX_GEOMETRY_ATOMIC_COUNTER_BUFFERS
#endif
#ifndef GL_MAX_GEOMETRY_ATOMIC_COUNTERS_EXT
#define GL_MAX_GEOMETRY_ATOMIC_COUNTERS_EXT GL_MAX_GEOMETRY_ATOMIC_COUNTERS
#endif
#ifndef GL_MAX_GEOMETRY_IMAGE_UNIFORMS_EXT
#define GL_MAX_GEOMETRY_IMAGE_UNIFORMS_EXT GL_MAX_GEOMETRY_IMAGE_UNIFORMS
#endif
#ifndef GL_MAX_GEOMETRY_SHADER_STORAGE_BLOCKS_EXT
#define GL_MAX_GEOMETRY_SHADER_STORAGE_BLOCKS_EXT GL_MAX_GEOMETRY_SHADER_STORAGE_BLOCKS
#endif
#ifndef GL_FIRST_VERTEX_CONVENTION_EXT
#define GL_FIRST_VERTEX_CONVENTION_EXT    GL_FIRST_VERTEX_CONVENTION
#endif
#ifndef GL_LAST_VERTEX_CONVENTION_EXT
#define GL_LAST_VERTEX_CONVENTION_EXT     GL_LAST_VERTEX_CONVENTION
#endif
#ifndef GL_UNDEFINED_VERTEX_EXT
#define GL_UNDEFINED_VERTEX_EXT           GL_UNDEFINED_VERTEX
#endif
#ifndef GL_PRIMITIVES_GENERATED_EXT
#define GL_PRIMITIVES_GENERATED_EXT       GL_PRIMITIVES_GENERATED
#endif
#ifndef GL_FRAMEBUFFER_DEFAULT_LAYERS_EXT
#define GL_FRAMEBUFFER_DEFAULT_LAYERS_EXT GL_FRAMEBUFFER_DEFAULT_LAYERS
#endif
#ifndef GL_MAX_FRAMEBUFFER_LAYERS_EXT
#define GL_MAX_FRAMEBUFFER_LAYERS_EXT     GL_MAX_FRAMEBUFFER_LAYERS
#endif
#ifndef GL_FRAMEBUFFER_INCOMPLETE_LAYER_TARGETS_EXT
#define GL_FRAMEBUFFER_INCOMPLETE_LAYER_TARGETS_EXT GL_FRAMEBUFFER_INCOMPLETE_LAYER_TARGETS
#endif
#ifndef GL_FRAMEBUFFER_ATTACHMENT_LAYERED_EXT
#define GL_FRAMEBUFFER_ATTACHMENT_LAYERED_EXT GL_FRAMEBUFFER_ATTACHMENT_LAYERED
#endif
#ifndef GL_REFERENCED_BY_GEOMETRY_SHADER_EXT
#define GL_REFERENCED_BY_GEOMETRY_SHADER_EXT GL_REFERENCED_BY_GEOMETRY_SHADER
#endif
#ifndef glFramebufferTextureEXT
#define glFramebufferTextureEXT           glFramebufferTexture
#endif
#endif /* GL_EXT_geometry_shader */

#ifndef GL_EXT_geometry_shader4
#define GL_EXT_geometry_shader4 1
#ifndef GL_GEOMETRY_VERTICES_OUT_EXT
#define GL_GEOMETRY_VERTICES_OUT_EXT      GL_GEOMETRY_VERTICES_OUT
#endif
#ifndef GL_GEOMETRY_INPUT_TYPE_EXT
#define GL_GEOMETRY_INPUT_TYPE_EXT        GL_GEOMETRY_INPUT_TYPE
#endif
#ifndef GL_GEOMETRY_OUTPUT_TYPE_EXT
#define GL_GEOMETRY_OUTPUT_TYPE_EXT       GL_GEOMETRY_OUTPUT_TYPE
#endif
#ifndef GL_MAX_GEOMETRY_VARYING_COMPONENTS_EXT
#define GL_MAX_GEOMETRY_VARYING_COMPONENTS_EXT GL_MAX_GEOMETRY_VARYING_COMPONENTS
#endif
#ifndef GL_MAX_VERTEX_VARYING_COMPONENTS_EXT
#define GL_MAX_VERTEX_VARYING_COMPONENTS_EXT GL_MAX_VERTEX_VARYING_COMPONENTS
#endif
#ifndef GL_MAX_VARYING_COMPONENTS_EXT
#define GL_MAX_VARYING_COMPONENTS_EXT     GL_MAX_VARYING_COMPONENTS
#endif
#ifndef GL_FRAMEBUFFER_INCOMPLETE_LAYER_COUNT_EXT
#define GL_FRAMEBUFFER_INCOMPLETE_LAYER_COUNT_EXT GL_FRAMEBUFFER_INCOMPLETE_LAYER_COUNT
#endif
#ifndef GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_LAYER_EXT
#define GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_LAYER_EXT GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_LAYER
#endif
#ifndef GL_PROGRAM_POINT_SIZE_EXT
#define GL_PROGRAM_POINT_SIZE_EXT         GL_PROGRAM_POINT_SIZE
#endif
#ifndef glProgramParameteriEXT
#define glProgramParameteriEXT            glProgramParameteri
#endif
#endif /* GL_EXT_geometry_shader4 */

#ifndef GL_EXT_gpu_shader5
#define GL_EXT_gpu_shader5 1
#endif /* GL_EXT_gpu_shader5 */

#ifndef GL_EXT_primitive_bounding_box
#define GL_EXT_primitive_bounding_box 1
#ifndef GL_PRIMITIVE_BOUNDING_BOX_EXT
#define GL_PRIMITIVE_BOUNDING_BOX_EXT     GL_PRIMITIVE_BOUNDING_BOX
#endif
#ifndef glPrimitiveBoundingBoxEXT
#define glPrimitiveBoundingBoxEXT         glPrimitiveBoundingBox
#endif
#endif /* GL_EXT_primitive_bounding_box */

#ifndef GL_EXT_shader_io_blocks
#define GL_EXT_shader_io_blocks 1
#endif /* GL_EXT_shader_io_blocks */

#ifndef GL_EXT_tessellation_shader
#define GL_EXT_tessellation_shader 1
#ifndef GL_PATCHES_EXT
#define GL_PATCHES_EXT                    GL_PATCHES
#endif
#ifndef GL_PATCH_VERTICES_EXT
#define GL_PATCH_VERTICES_EXT             GL_PATCH_VERTICES
#endif
#ifndef GL_TESS_CONTROL_OUTPUT_VERTICES_EXT
#define GL_TESS_CONTROL_OUTPUT_VERTICES_EXT GL_TESS_CONTROL_OUTPUT_VERTICES
#endif
#ifndef GL_TESS_GEN_MODE_EXT
#define GL_TESS_GEN_MODE_EXT              GL_TESS_GEN_MODE
#endif
#ifndef GL_TESS_GEN_SPACING_EXT
#define GL_TESS_GEN_SPACING_EXT           GL_TESS_GEN_SPACING
#endif
#ifndef GL_TESS_GEN_VERTEX_ORDER_EXT
#define GL_TESS_GEN_VERTEX_ORDER_EXT      GL_TESS_GEN_VERTEX_ORDER
#endif
#ifndef GL_TESS_GEN_POINT_MODE_EXT
#define GL_TESS_GEN_POINT_MODE_EXT        GL_TESS_GEN_POINT_MODE
#endif

#ifndef GL_ISOLINES_EXT
#define GL_ISOLINES_EXT                   GL_ISOLINES
#endif
#ifndef GL_QUADS_EXT
#define GL_QUADS_EXT                      GL_QUADS
#endif

#ifndef GL_FRACTIONAL_ODD_EXT
#define GL_FRACTIONAL_ODD_EXT             GL_FRACTIONAL_ODD
#endif
#ifndef GL_FRACTIONAL_EVEN_EXT
#define GL_FRACTIONAL_EVEN_EXT            GL_FRACTIONAL_EVEN
#endif


#ifndef GL_MAX_PATCH_VERTICES_EXT
#define GL_MAX_PATCH_VERTICES_EXT         GL_MAX_PATCH_VERTICES
#endif
#ifndef GL_MAX_TESS_GEN_LEVEL_EXT
#define GL_MAX_TESS_GEN_LEVEL_EXT         GL_MAX_TESS_GEN_LEVEL
#endif
#ifndef GL_MAX_TESS_CONTROL_UNIFORM_COMPONENTS_EXT
#define GL_MAX_TESS_CONTROL_UNIFORM_COMPONENTS_EXT GL_MAX_TESS_CONTROL_UNIFORM_COMPONENTS
#endif
#ifndef GL_MAX_TESS_EVALUATION_UNIFORM_COMPONENTS_EXT
#define GL_MAX_TESS_EVALUATION_UNIFORM_COMPONENTS_EXT GL_MAX_TESS_EVALUATION_UNIFORM_COMPONENTS
#endif
#ifndef GL_MAX_TESS_CONTROL_TEXTURE_IMAGE_UNITS_EXT
#define GL_MAX_TESS_CONTROL_TEXTURE_IMAGE_UNITS_EXT GL_MAX_TESS_CONTROL_TEXTURE_IMAGE_UNITS
#endif
#ifndef GL_MAX_TESS_EVALUATION_TEXTURE_IMAGE_UNITS_EXT
#define GL_MAX_TESS_EVALUATION_TEXTURE_IMAGE_UNITS_EXT GL_MAX_TESS_EVALUATION_TEXTURE_IMAGE_UNITS
#endif
#ifndef GL_MAX_TESS_CONTROL_OUTPUT_COMPONENTS_EXT
#define GL_MAX_TESS_CONTROL_OUTPUT_COMPONENTS_EXT GL_MAX_TESS_CONTROL_OUTPUT_COMPONENTS
#endif
#ifndef GL_MAX_TESS_PATCH_COMPONENTS_EXT
#define GL_MAX_TESS_PATCH_COMPONENTS_EXT  GL_MAX_TESS_PATCH_COMPONENTS
#endif
#ifndef GL_MAX_TESS_CONTROL_TOTAL_OUTPUT_COMPONENTS_EXT
#define GL_MAX_TESS_CONTROL_TOTAL_OUTPUT_COMPONENTS_EXT GL_MAX_TESS_CONTROL_TOTAL_OUTPUT_COMPONENTS
#endif
#ifndef GL_MAX_TESS_EVALUATION_OUTPUT_COMPONENTS_EXT
#define GL_MAX_TESS_EVALUATION_OUTPUT_COMPONENTS_EXT GL_MAX_TESS_EVALUATION_OUTPUT_COMPONENTS
#endif
#ifndef GL_MAX_TESS_CONTROL_UNIFORM_BLOCKS_EXT
#define GL_MAX_TESS_CONTROL_UNIFORM_BLOCKS_EXT GL_MAX_TESS_CONTROL_UNIFORM_BLOCKS
#endif
#ifndef GL_MAX_TESS_EVALUATION_UNIFORM_BLOCKS_EXT
#define GL_MAX_TESS_EVALUATION_UNIFORM_BLOCKS_EXT GL_MAX_TESS_EVALUATION_UNIFORM_BLOCKS
#endif
#ifndef GL_MAX_TESS_CONTROL_INPUT_COMPONENTS_EXT
#define GL_MAX_TESS_CONTROL_INPUT_COMPONENTS_EXT GL_MAX_TESS_CONTROL_INPUT_COMPONENTS
#endif
#ifndef GL_MAX_TESS_EVALUATION_INPUT_COMPONENTS_EXT
#define GL_MAX_TESS_EVALUATION_INPUT_COMPONENTS_EXT GL_MAX_TESS_EVALUATION_INPUT_COMPONENTS
#endif
#ifndef GL_MAX_COMBINED_TESS_CONTROL_UNIFORM_COMPONENTS_EXT
#define GL_MAX_COMBINED_TESS_CONTROL_UNIFORM_COMPONENTS_EXT GL_MAX_COMBINED_TESS_CONTROL_UNIFORM_COMPONENTS
#endif
#ifndef GL_MAX_COMBINED_TESS_EVALUATION_UNIFORM_COMPONENTS_EXT
#define GL_MAX_COMBINED_TESS_EVALUATION_UNIFORM_COMPONENTS_EXT GL_MAX_COMBINED_TESS_EVALUATION_UNIFORM_COMPONENTS
#endif
#ifndef GL_MAX_TESS_CONTROL_ATOMIC_COUNTER_BUFFERS_EXT
#define GL_MAX_TESS_CONTROL_ATOMIC_COUNTER_BUFFERS_EXT GL_MAX_TESS_CONTROL_ATOMIC_COUNTER_BUFFERS
#endif
#ifndef GL_MAX_TESS_EVALUATION_ATOMIC_COUNTER_BUFFERS_EXT
#define GL_MAX_TESS_EVALUATION_ATOMIC_COUNTER_BUFFERS_EXT GL_MAX_TESS_EVALUATION_ATOMIC_COUNTER_BUFFERS
#endif
#ifndef GL_MAX_TESS_CONTROL_ATOMIC_COUNTERS_EXT
#define GL_MAX_TESS_CONTROL_ATOMIC_COUNTERS_EXT GL_MAX_TESS_CONTROL_ATOMIC_COUNTERS
#endif
#ifndef GL_MAX_TESS_EVALUATION_ATOMIC_COUNTERS_EXT
#define GL_MAX_TESS_EVALUATION_ATOMIC_COUNTERS_EXT GL_MAX_TESS_EVALUATION_ATOMIC_COUNTERS
#endif
#ifndef GL_MAX_TESS_CONTROL_IMAGE_UNIFORMS_EXT
#define GL_MAX_TESS_CONTROL_IMAGE_UNIFORMS_EXT GL_MAX_TESS_CONTROL_IMAGE_UNIFORMS
#endif
#ifndef GL_MAX_TESS_EVALUATION_IMAGE_UNIFORMS_EXT
#define GL_MAX_TESS_EVALUATION_IMAGE_UNIFORMS_EXT GL_MAX_TESS_EVALUATION_IMAGE_UNIFORMS
#endif
#ifndef GL_MAX_TESS_CONTROL_SHADER_STORAGE_BLOCKS_EXT
#define GL_MAX_TESS_CONTROL_SHADER_STORAGE_BLOCKS_EXT GL_MAX_TESS_CONTROL_SHADER_STORAGE_BLOCKS
#endif
#ifndef GL_MAX_TESS_EVALUATION_SHADER_STORAGE_BLOCKS_EXT
#define GL_MAX_TESS_EVALUATION_SHADER_STORAGE_BLOCKS_EXT GL_MAX_TESS_EVALUATION_SHADER_STORAGE_BLOCKS
#endif

#ifndef GL_IS_PER_PATCH_EXT
#define GL_IS_PER_PATCH_EXT               GL_IS_PER_PATCH
#endif
#ifndef GL_REFERENCED_BY_TESS_CONTROL_SHADER_EXT
#define GL_REFERENCED_BY_TESS_CONTROL_SHADER_EXT GL_REFERENCED_BY_TESS_CONTROL_SHADER
#endif
#ifndef GL_REFERENCED_BY_TESS_EVALUATION_SHADER_EXT
#define GL_REFERENCED_BY_TESS_EVALUATION_SHADER_EXT GL_REFERENCED_BY_TESS_EVALUATION_SHADER
#endif
#ifndef GL_TESS_CONTROL_SHADER_EXT
#define GL_TESS_CONTROL_SHADER_EXT        GL_TESS_CONTROL_SHADER
#endif
#ifndef GL_TESS_EVALUATION_SHADER_EXT
#define GL_TESS_EVALUATION_SHADER_EXT     GL_TESS_EVALUATION_SHADER
#endif
#ifndef GL_TESS_CONTROL_SHADER_BIT_EXT
#define GL_TESS_CONTROL_SHADER_BIT_EXT    GL_TESS_CONTROL_SHADER_BIT
#endif
#ifndef GL_TESS_EVALUATION_SHADER_BIT_EXT
#define GL_TESS_EVALUATION_SHADER_BIT_EXT GL_TESS_EVALUATION_SHADER_BIT
#endif
#ifndef glPatchParameteriEXT
#define glPatchParameteriEXT              glPatchParameteri
#endif
#endif /* GL_EXT_tessellation_shader */

#ifndef GL_EXT_texture_border_clamp
#define GL_EXT_texture_border_clamp 1
#ifndef GL_TEXTURE_BORDER_COLOR_EXT
#define GL_TEXTURE_BORDER_COLOR_EXT       GL_TEXTURE_BORDER_COLOR
#endif
#ifndef GL_CLAMP_TO_BORDER_EXT
#define GL_CLAMP_TO_BORDER_EXT            GL_CLAMP_TO_BORDER
#endif
#ifndef glTexParameterIivEXT
#define glTexParameterIivEXT              glTexParameterIiv
#endif
#ifndef glTexParameterIuivEXT
#define glTexParameterIuivEXT             glTexParameterIuiv
#endif
#ifndef glGetTexParameterIivEXT
#define glGetTexParameterIivEXT           glGetTexParameterIiv
#endif
#ifndef glGetTexParameterIuivEXT
#define glGetTexParameterIuivEXT          glGetTexParameterIuiv
#endif
#ifndef glSamplerParameterIivEXT
#define glSamplerParameterIivEXT          glSamplerParameterIiv
#endif
#ifndef glSamplerParameterIuivEXT
#define glSamplerParameterIuivEXT         glSamplerParameterIuiv
#endif
#ifndef glGetSamplerParameterIivEXT
#define glGetSamplerParameterIivEXT       glGetSamplerParameterIiv
#endif
#ifndef glGetSamplerParameterIuivEXT
#define glGetSamplerParameterIuivEXT      glGetSamplerParameterIuiv
#endif
#endif /* GL_EXT_texture_border_clamp */

#ifndef GL_EXT_texture_buffer
#define GL_EXT_texture_buffer 1
#ifndef GL_TEXTURE_BUFFER_EXT
#define GL_TEXTURE_BUFFER_EXT             GL_TEXTURE_BUFFER
#endif
#ifndef GL_TEXTURE_BUFFER_BINDING_EXT
#define GL_TEXTURE_BUFFER_BINDING_EXT     GL_TEXTURE_BUFFER_BINDING
#endif
#ifndef GL_MAX_TEXTURE_BUFFER_SIZE_EXT
#define GL_MAX_TEXTURE_BUFFER_SIZE_EXT    GL_MAX_TEXTURE_BUFFER_SIZE
#endif
#ifndef GL_TEXTURE_BINDING_BUFFER_EXT
#define GL_TEXTURE_BINDING_BUFFER_EXT     GL_TEXTURE_BINDING_BUFFER
#endif
#ifndef GL_TEXTURE_BUFFER_DATA_STORE_BINDING_EXT
#define GL_TEXTURE_BUFFER_DATA_STORE_BINDING_EXT GL_TEXTURE_BUFFER_DATA_STORE_BINDING
#endif
#ifndef GL_TEXTURE_BUFFER_OFFSET_ALIGNMENT_EXT
#define GL_TEXTURE_BUFFER_OFFSET_ALIGNMENT_EXT GL_TEXTURE_BUFFER_OFFSET_ALIGNMENT
#endif
#ifndef GL_SAMPLER_BUFFER_EXT
#define GL_SAMPLER_BUFFER_EXT             GL_SAMPLER_BUFFER
#endif
#ifndef GL_INT_SAMPLER_BUFFER_EXT
#define GL_INT_SAMPLER_BUFFER_EXT         GL_INT_SAMPLER_BUFFER
#endif
#ifndef GL_UNSIGNED_INT_SAMPLER_BUFFER_EXT
#define GL_UNSIGNED_INT_SAMPLER_BUFFER_EXT GL_UNSIGNED_INT_SAMPLER_BUFFER
#endif
#ifndef GL_IMAGE_BUFFER_EXT
#define GL_IMAGE_BUFFER_EXT               GL_IMAGE_BUFFER
#endif
#ifndef GL_INT_IMAGE_BUFFER_EXT
#define GL_INT_IMAGE_BUFFER_EXT           GL_INT_IMAGE_BUFFER
#endif
#ifndef GL_UNSIGNED_INT_IMAGE_BUFFER_EXT
#define GL_UNSIGNED_INT_IMAGE_BUFFER_EXT  GL_UNSIGNED_INT_IMAGE_BUFFER
#endif
#ifndef GL_TEXTURE_BUFFER_OFFSET_EXT
#define GL_TEXTURE_BUFFER_OFFSET_EXT      GL_TEXTURE_BUFFER_OFFSET
#endif
#ifndef GL_TEXTURE_BUFFER_SIZE_EXT
#define GL_TEXTURE_BUFFER_SIZE_EXT        GL_TEXTURE_BUFFER_SIZE
#endif
#ifndef glTexBufferEXT
#define glTexBufferEXT                    glTexBuffer
#endif
#ifndef glTexBufferRangeEXT
#define glTexBufferRangeEXT               glTexBufferRange
#endif
#endif /* GL_EXT_texture_buffer */

#ifndef GL_EXT_texture_buffer_object
#define GL_EXT_texture_buffer_object 1
#ifndef GL_TEXTURE_BUFFER_FORMAT_EXT
#define GL_TEXTURE_BUFFER_FORMAT_EXT      GL_TEXTURE_BUFFER_FORMAT
#endif
#endif /* GL_EXT_texture_buffer_object */

#ifndef GL_EXT_texture_cube_map_array
#define GL_EXT_texture_cube_map_array 1
#ifndef GL_TEXTURE_CUBE_MAP_ARRAY_EXT
#define GL_TEXTURE_CUBE_MAP_ARRAY_EXT     GL_TEXTURE_CUBE_MAP_ARRAY
#endif
#ifndef GL_TEXTURE_BINDING_CUBE_MAP_ARRAY_EXT
#define GL_TEXTURE_BINDING_CUBE_MAP_ARRAY_EXT GL_TEXTURE_BINDING_CUBE_MAP_ARRAY
#endif
#ifndef GL_SAMPLER_CUBE_MAP_ARRAY_EXT
#define GL_SAMPLER_CUBE_MAP_ARRAY_EXT     GL_SAMPLER_CUBE_MAP_ARRAY
#endif
#ifndef GL_SAMPLER_CUBE_MAP_ARRAY_SHADOW_EXT
#define GL_SAMPLER_CUBE_MAP_ARRAY_SHADOW_EXT GL_SAMPLER_CUBE_MAP_ARRAY_SHADOW
#endif
#ifndef GL_INT_SAMPLER_CUBE_MAP_ARRAY_EXT
#define GL_INT_SAMPLER_CUBE_MAP_ARRAY_EXT GL_INT_SAMPLER_CUBE_MAP_ARRAY
#endif
#ifndef GL_UNSIGNED_INT_SAMPLER_CUBE_MAP_ARRAY_EXT
#define GL_UNSIGNED_INT_SAMPLER_CUBE_MAP_ARRAY_EXT GL_UNSIGNED_INT_SAMPLER_CUBE_MAP_ARRAY
#endif
#ifndef GL_IMAGE_CUBE_MAP_ARRAY_EXT
#define GL_IMAGE_CUBE_MAP_ARRAY_EXT       GL_IMAGE_CUBE_MAP_ARRAY
#endif
#ifndef GL_INT_IMAGE_CUBE_MAP_ARRAY_EXT
#define GL_INT_IMAGE_CUBE_MAP_ARRAY_EXT   GL_INT_IMAGE_CUBE_MAP_ARRAY
#endif
#ifndef GL_UNSIGNED_INT_IMAGE_CUBE_MAP_ARRAY_EXT
#define GL_UNSIGNED_INT_IMAGE_CUBE_MAP_ARRAY_EXT GL_UNSIGNED_INT_IMAGE_CUBE_MAP_ARRAY
#endif
#endif /* GL_EXT_texture_cube_map_array */

#ifdef __cplusplus
}
#endif

#endif
